export const HARDCODED_POSTS = [
    { 
      image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&q=80&w=800", 
      title: "Why India's Manufacturing Sector Needs a Materials Intelligence Platform", 
      date: "07/09/2026", author: "MatDataHub Editorial", readTime: "6 min", tag: "Industry", featured: true,
      featureName: "Explore Materials Database", featureLink: "/materials",
      excerpt: "India's PLI schemes and Make in India 2.0 are fueling a manufacturing renaissance — but 73% of engineers still rely on outdated PDF datasheets. Here's how digital materials intelligence is closing that gap.",
      content: `India's manufacturing sector is projected to reach $1 trillion by 2028. With the Production-Linked Incentive (PLI) schemes spanning 14 sectors — from semiconductors to advanced chemistry cell batteries — the demand for accurate, real-time materials data has never been higher.\n\n## The Problem: Fragmented Material Data\n\nMost Indian manufacturers still rely on:\n- Scattered PDF datasheets from suppliers\n- Outdated IS/BIS standard handbooks\n- Word-of-mouth material recommendations\n\nThis leads to **over-engineering** (safety factors of 3x when 1.5x would suffice), **cost overruns** (selecting premium alloys when equivalent grades exist at 40% lower cost), and **compliance gaps** (missing EU-CBAM carbon declarations).\n\n## The Solution: MatDataHub\n\nMatDataHub provides a single source of truth — verified mechanical, thermal, and economic properties for 500+ engineering materials, mapped to ASTM/ISO/BIS standards. Our AI-powered substitution engine finds cost-optimal alternatives in seconds, not weeks.\n\n**Key features that matter for Indian manufacturers:**\n- Side-by-side comparison of IS 2062 vs ASTM A36 vs EN 10025\n- Real-time cost benchmarking in INR\n- EU-CBAM carbon tax calculator for export compliance\n- Bill of Materials analyzer with automated material matching`
    },
    { 
      image: "https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&q=80&w=800", 
      title: "Modeling Thermal Expansion in Aerospace Alloys: Ti-6Al-4V vs Al 7075-T6", 
      date: "04/09/2026", author: "Dr. Alara Vance", readTime: "8 min", tag: "Physics", featured: false,
      featureName: "Try Compare Tool", featureLink: "/analytics/compare",
      excerpt: "Deep dive into isotropic thermal expansion formulas and why Titanium out-performs Aluminum 7075 at Mach 2.5 flight profiles.",
      content: `Thermal expansion is a critical design parameter in aerospace structures. When an aircraft fuselage transitions from ground temperature (+40°C in Chennai) to cruise altitude (-56°C at FL410), every rivet, skin panel, and spar cap must accommodate differential expansion.\n\n## The CTE Equation\n\nLinear thermal expansion is governed by:\n\nΔL = L₀ × α × ΔT\n\nWhere:\n- ΔL = change in length (m)\n- L₀ = original length (m)\n- α = coefficient of thermal expansion (CTE, in /°C)\n- ΔT = temperature change (°C)\n\n## Ti-6Al-4V vs Al 7075-T6\n\n| Property | Ti-6Al-4V | Al 7075-T6 |\n|---|---|---|\n| CTE (20-300°C) | 8.6 × 10⁻⁶ /°C | 23.6 × 10⁻⁶ /°C |\n| Density | 4.43 g/cm³ | 2.81 g/cm³ |\n| Yield Strength | 880 MPa | 503 MPa |\n| Specific Strength | 198 kNm/kg | 179 kNm/kg |\n\nAt Mach 2.5, skin temperatures reach ~180°C. For a 10-meter fuselage panel:\n- Al 7075: ΔL = 10 × 23.6e-6 × 160 = **37.8 mm** expansion\n- Ti-6Al-4V: ΔL = 10 × 8.6e-6 × 160 = **13.8 mm** expansion\n\nTitanium's CTE is 2.7× lower, reducing thermal stress concentrations at fastener holes by 63%.\n\n**Use MatDataHub's Side-by-Side Compare tool to instantly visualize these differences across any two alloys.**`
    },
    { 
      image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=800", 
      title: "EU-CBAM 2026: A Practical Guide for Indian Steel Exporters", 
      date: "22/08/2026", author: "ESG Policy Team", readTime: "5 min", tag: "Economics", featured: true,
      featureName: "Try CBAM Calculator", featureLink: "/analytics/cbam",
      excerpt: "The EU Carbon Border Adjustment Mechanism is now mandatory. Here's how to calculate your CBAM liability using MatDataHub's built-in analyzer.",
      content: `Starting January 2026, the European Union's Carbon Border Adjustment Mechanism (CBAM) requires all importers of steel, aluminum, cement, fertilizers, electricity, and hydrogen to purchase CBAM certificates based on the embedded carbon content of their goods.\n\n## What Indian Exporters Must Know\n\n1. **Reporting is mandatory** — even for small consignments\n2. **Default values are punitive** — if you don't declare your actual emissions, the EU will apply the worst-performing 10% benchmark\n3. **Certificate price tracks EU ETS** — currently ~€75/tonne CO₂e\n\n## Calculating CBAM Liability\n\nFor every tonne of steel exported:\n- India's average BF-BOF steel: ~2.5 t CO₂e/t steel\n- EU reference benchmark: ~1.52 t CO₂e/t steel\n- CBAM-liable emissions: 2.5 - 1.52 = **0.98 t CO₂e/t steel**\n- Cost: 0.98 × €75 = **€73.50 per tonne of steel**\n\nFor a 10,000-tonne annual export contract, that's **€735,000** in CBAM certificates.\n\n## How MatDataHub Helps\n\nUpload your Bill of Materials CSV to our **CBAM Calculator** (Analytics → CBAM Analyzer). It automatically:\n- Matches your materials to our verified emissions database (ICE DB v3)\n- Calculates embedded carbon per component\n- Estimates total CBAM liability in EUR\n- Generates a compliance-ready report`
    },
    { 
      image: "https://images.unsplash.com/photo-1616423640778-28d1b53229bd?auto=format&fit=crop&q=80&w=800", 
      title: "Rule of Mixtures vs Halpin-Tsai: Which Model for Your Composite?", 
      date: "15/08/2026", author: "Prof. H. Chen", readTime: "12 min", tag: "Mathematics", featured: false,
      featureName: "Try Composite Synthesizer", featureLink: "/analytics/synthesizer",
      excerpt: "Comparing mathematical models for predicting the transverse elastic modulus of continuous fiber composites — with worked examples.",
      content: `When designing a carbon fiber reinforced polymer (CFRP) laminate, the most fundamental question is: what will the elastic modulus be?\n\n## Rule of Mixtures (Voigt Model)\n\nFor longitudinal modulus (fiber direction):\n\nE₁ = Ef × Vf + Em × (1 - Vf)\n\nThis is exact for iso-strain conditions (loading parallel to fibers).\n\n## Inverse Rule of Mixtures (Reuss Model)\n\nFor transverse modulus:\n\n1/E₂ = Vf/Ef + (1 - Vf)/Em\n\nThis dramatically underestimates transverse stiffness because it assumes iso-stress.\n\n## Halpin-Tsai Model\n\nA semi-empirical correction:\n\nE₂ = Em × (1 + ξηVf) / (1 - ηVf)\n\nWhere η = (Ef/Em - 1) / (Ef/Em + ξ) and ξ is a geometry factor (typically 2 for circular fibers).\n\n## Worked Example: T300/Epoxy\n\n| Property | Carbon Fiber (T300) | Epoxy Matrix |\n|---|---|---|\n| E (GPa) | 230 | 3.5 |\n| Vf | 0.60 | 0.40 |\n\n- **ROM (E₁):** 230×0.6 + 3.5×0.4 = **139.4 GPa** ✓\n- **Inverse ROM (E₂):** 1/(0.6/230 + 0.4/3.5) = **8.56 GPa** (too low)\n- **Halpin-Tsai (E₂):** ξ=2, η=0.970 → **13.2 GPa** (matches experiments)\n\n**MatDataHub's Composite Synthesizer uses both ROM and inverse ROM bounds.** Our analytics engine shows you the full design envelope.`
    },
    { 
      image: "https://images.unsplash.com/photo-1580983592398-44fb780281b3?auto=format&fit=crop&q=80&w=800", 
      title: "Selecting the Right Stainless Steel Grade: 304 vs 316 vs 430 vs 2205", 
      date: "01/08/2026", author: "MetalTech Research", readTime: "7 min", tag: "Materials", featured: false,
      featureName: "Try AI Material Advisor", featureLink: "/dashboard",
      excerpt: "A practical decision matrix for choosing stainless steel grades based on corrosion environment, cost, and mechanical requirements.",
      content: `Stainless steel accounts for 52% of all material queries on MatDataHub. Here's a definitive comparison of the four most-used grades.\n\n## Quick Comparison\n\n| Property | AISI 304 | AISI 316 | AISI 430 | Duplex 2205 |\n|---|---|---|---|---|\n| Type | Austenitic | Austenitic | Ferritic | Duplex |\n| Cr (%) | 18-20 | 16-18 | 16-18 | 22-23 |\n| Ni (%) | 8-10.5 | 10-14 | <0.75 | 4.5-6.5 |\n| Mo (%) | — | 2-3 | — | 3-3.5 |\n| Yield (MPa) | 205 | 205 | 205 | 450 |\n| Cost (₹/kg) | 220-280 | 320-400 | 150-200 | 450-600 |\n| Pitting Resistance (PREN) | 18 | 24 | 16 | 35 |\n\n## Decision Rules\n\n1. **General purpose / Food grade** → 304 (best value)\n2. **Marine / Chloride exposure** → 316 (Mo provides pitting resistance)\n3. **Budget-constrained, no corrosion** → 430 (no Nickel = 40% cheaper)\n4. **High strength + corrosion** → 2205 (2× yield of 304, superior PREN)\n\n**Use MatDataHub's AI Material Advisor** — just type \"I need a stainless steel for marine heat exchangers under ₹400/kg\" and get instant, database-backed recommendations.`
    },
    { 
      image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&q=80&w=800", 
      title: "How to Reduce Manufacturing Costs by 25% with Smart Material Substitution", 
      date: "18/07/2026", author: "MatDataHub Engineering", readTime: "6 min", tag: "Industry", featured: true,
      featureName: "Try AI Substitution", featureLink: "/analytics/substitution",
      excerpt: "Real case study: An automotive OEM replaced 3 materials in their EV battery enclosure using our AI substitution engine, saving ₹2.3 Cr annually.",
      content: `Material costs typically represent 40-60% of total manufacturing cost in automotive, aerospace, and industrial equipment. Yet most companies stick with legacy material selections — because finding equivalent alternatives requires weeks of manual research.\n\n## Case Study: EV Battery Enclosure Redesign\n\nAn Indian automotive OEM was manufacturing battery enclosures using:\n1. Al 6061-T6 for the main tray (₹380/kg)\n2. AISI 316L for mounting brackets (₹380/kg)\n3. FR-4 Glass Epoxy for insulation panels (₹520/kg)\n\n**Using MatDataHub's Smart AI Substitution tool:**\n\n| Original | Substitution | Match Score | Cost Saving |\n|---|---|---|---|\n| Al 6061-T6 | Al 5052-H32 | 94.2% | -32% (₹258/kg) |\n| AISI 316L | AISI 304 | 91.7% | -28% (₹274/kg) |\n| FR-4 | Nomex 410 | 87.5% | -18% (₹426/kg) |\n\n**Annual production: 50,000 units → Total savings: ₹2.3 Crore/year**\n\nThe substitution engine uses Euclidean distance in a normalized N-dimensional property space (density, tensile strength, thermal conductivity, cost) with user-adjustable importance weights.\n\n**Try it yourself:** Go to Analytics → Smart AI Substitution, select your base material, adjust the weight sliders, and discover cost-optimal alternatives in seconds.`
    },
    { 
      image: "https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&q=80&w=800", 
      title: "Understanding Embodied Carbon: A Materials Engineer's Guide", 
      date: "05/07/2026", author: "Dr. S. Krishnamurthy", readTime: "9 min", tag: "Sustainability", featured: false,
      featureName: "Try CBAM Calculator", featureLink: "/analytics/cbam",
      excerpt: "From cradle-to-gate emissions to ICE database factors — everything you need to know about carbon accounting for engineering materials.",
      content: `Embodied carbon (EC) represents the total greenhouse gas emissions associated with extracting, processing, manufacturing, and transporting a material — measured in kg CO₂e per kg of material.\n\n## Why It Matters Now\n\n- EU CBAM makes embodied carbon a direct cost factor\n- Green procurement mandates in public infrastructure (Indian Railways, NHAI)\n- ESG reporting requirements for listed companies (BRSR framework)\n\n## Key Emission Factors (ICE Database v3)\n\n| Material | EC (kg CO₂e/kg) | Notes |\n|---|---|---|\n| General Steel | 1.85 | BF-BOF route |\n| Stainless Steel (304) | 6.15 | High Ni/Cr content |\n| Aluminum (primary) | 8.24 | Electrolysis-intensive |\n| Aluminum (recycled) | 0.52 | 94% reduction |\n| Titanium | 35.7 | Kroll process |\n| CFRP | 29.5 | Energy-intensive PAN fiber |\n| Concrete | 0.13 | Volume-driven impact |\n| Copper | 3.81 | Smelting + refining |\n\n## The Recycling Multiplier\n\nRecycled aluminum has 94% lower EC than primary. This is why MatDataHub tracks recyclability indices alongside carbon factors — a material with high EC but high recyclability (like aluminum) has a very different lifecycle impact than one with moderate EC but zero recyclability (like thermoset composites).\n\n**MatDataHub's CBAM Calculator uses these exact ICE v3 factors** as fallback values when your database materials don't have measured emissions data.`
    },
    { 
      image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=800", 
      title: "Beam Deflection Calculator: The Physics Behind MatDataHub's Workspace Tool", 
      date: "20/06/2026", author: "Structural Mechanics Team", readTime: "10 min", tag: "Physics", featured: false,
      featureName: "Explore Workspaces", featureLink: "/projects",
      excerpt: "Euler-Bernoulli beam theory, moment of inertia calculations, and how we validate our deflection predictions against FEA benchmarks.",
      content: `MatDataHub's Workspace includes a built-in beam deflection calculator. Here's the engineering science behind it.\n\n## Euler-Bernoulli Beam Theory\n\nFor a simply-supported beam with a point load P at midspan:\n\nδ_max = PL³ / (48EI)\n\nWhere:\n- δ_max = maximum deflection (m)\n- P = applied load (N)\n- L = span length (m)\n- E = elastic modulus (Pa)\n- I = second moment of area (m⁴)\n\n## For a cantilever with end load:\n\nδ_max = PL³ / (3EI)\n\n## Practical Example\n\nA 2-meter cantilever shelf bracket made from AISI 304 stainless steel (E = 193 GPa), rectangular cross-section 50mm × 10mm, supporting 50 kg:\n\n- P = 50 × 9.81 = 490.5 N\n- I = (0.05 × 0.01³) / 12 = 4.167 × 10⁻⁹ m⁴\n- δ = (490.5 × 2³) / (3 × 193e9 × 4.167e-9)\n- δ = 3924 / 2412.7 = **1.63 mm**\n\nThis is within the L/500 serviceability limit (4mm), so the design is acceptable.\n\n**MatDataHub automatically pulls the elastic modulus from our verified database** when you select a material in the Workspace, eliminating manual lookup errors.`
    }
  ];
